### ISSUE TITLE
I2C Error with pico_status_hv3.0.py

### ISSUE THREAD

**Issue by cowsay652** [modmypi/PiModules#14]
Hi,
I am using a Raspberry Pi 3 and the UPS PIco HV3.0B Stack 450. I have installed everything according to your instructions, but when I run `pico_status_hv3.0.py` from [here](https://github.com/modmypi/PiModules/blob/master/pico_status/pico_status_hv3.0.py), it gives me this:
```python
Traceback (most recent call last):
  File "pico_status_hv3.0.py", line 186, in <module>
    print " ","UPS PIco Firmware.....:",fw_version()
  File "pico_status_hv3.0.py", line 29, in fw_version
    data = i2c.read_byte_data(0x69, 0x26)
IOError: [Errno 121] Remote I/O error
```
The UPS *does* work - the lights come on correctly, fssd works, and when I take the main power out, the battery kicks in.
I am using Python 2.7, and have enabled I2C, so I'm not quite sure what the problem is...

Any help would be appreciated :)

**Comment by cowsay652** [comment]
Never mind - it works now.
I think that like the GPIO pins weren't making contact.
